cadence response to interface preserved number and boolean types
bjartek/overflow pull request #44
Opened 2022-07-13 02:25 UTC by austinkline

Currently everything in the overflow json response from a cadence value are all strings. This changes that and attempts to preserve the type of the cadence value

2022-07-13 06:29 UTC, bjartek commented
Working on v1 in rhe api branch. Good tests! Can you check there? This is actually a breaking change so I want it in the new version

2022-07-13 07:50 UTC, bjartek requested changes

2022-07-13 07:50 UTC, bjartek commented on overflow/utils.go
> +func CadenceValueToGoValue(input cadence.Value) (output interface{}) {
There are a lot more corner cases then this, look in the API branch for all the fun!

2022-07-13 18:19 UTC, austinkline commented on overflow/utils.go
> +func CadenceValueToGoValue(input cadence.Value) (output interface{}) {
Well your approach is definitely better for UFix and Fix parsing:
https://github.com/bjartek/overflow/blob/api/overflow/cadence.go#L97

Doesn't seem like that many more edge cases for primitive types, though? I think you found the same general end-state that the special needs are [U]Int, [U]Fix, and Address

2022-07-13 18:19 UTC, austinkline commented
> Working on v1 in rhe api branch. Good tests! Can you check there? This is actually a breaking change so I want it in the new version

Makes sense! I can just add the test if that's all that's needed. Seems like v1 handles all of the same things this PR changes

2022-07-19 14:38 UTC, bjartek commented
This is already fixed i belive.

2022-07-19 14:38 UTC, closed without merging